Repository cloudforet-io/plugin-nhncloud-inven-collector, pull requests merged in 2024-08, with the labels that each got.

#28 feat: add release github actions script
  .github/workflows/dispatch_release.yaml
Labels: pass/signedoff

#31 Add missing import statement
  src/plugin/manager/__init__.py
Labels: pass/signedoff

#35 Add region collecting logic
  src/plugin/conf/cloud_service_conf.py
  src/plugin/main.py
  src/plugin/manager/base.py
Labels: pass/signedoff

#32 Push, Email error handling
  src/plugin/manager/email/category_manager.py
  src/plugin/manager/email/tag_manager.py
  src/plugin/manager/email/template_manager.py
  src/plugin/manager/push/tag_manager.py
  src/plugin/manager/push/token_manager.py
Labels: pass/signedoff

#33 Ignore collecting dns when the service is inactivated
  src/plugin/connector/dns_plus/dns_zone_connector.py
  src/plugin/connector/dns_plus/gslb_connector.py
  src/plugin/connector/dns_plus/health_check_connector.py
  src/plugin/connector/dns_plus/pool_connector.py
Labels: pass/signedoff

#38 Fix lost nks managers with labels
  src/plugin/manager/__init__.py
  src/plugin/manager/nks/__init__.py
  src/plugin/manager/nks/group_manager.py
  src/plugin/manager/nks/nks_manager.py
  src/plugin/metadata/nks/group.yaml
  src/plugin/metadata/nks/nks.yaml
Labels: bug, pass/signedoff

#42 Add Object Storage connector & metadata
  src/plugin/connector/object_storage/container_connector.py
  src/plugin/metadata/object_storage/container.yaml
Labels: pass/signedoff

#45 Fix paging in LoadBalancer Secret (TODO)
  src/plugin/connector/loadbalancer/secret_connector.py
Labels: enhancement, pass/signedoff

#47 Add object storage collecting logic
  managed_resource/schema/nhncloud_object_storage_access_key.yaml
  managed_resource/schema/nhncloud_service_account.yaml
  src/plugin/conf/cloud_service_conf.py
  src/plugin/connector/object_storage/__init__.py
  src/plugin/connector/object_storage/container_connector.py
  src/plugin/manager/__init__.py
  src/plugin/manager/base.py
  src/plugin/manager/object_storage/__init__.py
  src/plugin/manager/object_storage/container_manager.py
Labels: pass/signedoff

#48 Add collector description
  managed_resource/plugin/collector.yaml
Labels: pass/signedoff

#50 Add storage size column in block storage
  src/plugin/manager/block_storage/block_storage_manager.py
Labels: enhancement, pass/signedoff

#51 Update metadata with listeners
  src/plugin/connector/loadbalancer/listener_connector.py
  src/plugin/manager/loadbalancer/loadbalancer_manager.py
  src/plugin/metadata/loadbalancer/listeners.yaml
  src/plugin/metadata/loadbalancer/loadbalancer.yaml
Labels: enhancement, pass/signedoff

#52 Add guides for NHN Plugin docs
  docs/en/GUIDE-img/access-key-info-1.png
  docs/en/GUIDE-img/access-key-info-2.png
  docs/en/GUIDE-img/account-info-1.png
  docs/en/GUIDE-img/account-info-2.png
  docs/en/GUIDE-img/account-info-3.png
  docs/en/GUIDE-img/account-info-4.png
  docs/en/GUIDE-img/account-info-5.png
  docs/en/GUIDE-img/app-key-info-1.png
  docs/en/GUIDE-img/app-key-info-2.png
  docs/en/GUIDE-img/app-key-info-3.png
  docs/en/GUIDE-img/app-key-info-4.png
  docs/en/GUIDE-img/app-key-info-5.png
  docs/en/GUIDE-img/app-key-info-6.png
  docs/en/GUIDE-img/app-key-info-7.png
  docs/en/GUIDE-img/app-key-info-8.png
  docs/en/GUIDE-img/certificate-app-key-info-1.png
  docs/en/GUIDE-img/certificate-app-key-info-2.png
  docs/en/GUIDE-img/nhn-cloud.svg
  docs/en/GUIDE-img/service-info.png
  docs/en/GUIDE-img/storage-access-key-info-1.png
  docs/en/GUIDE-img/storage-access-key-info-2.png
  docs/en/GUIDE.md
  docs/ko/GUIDE-img/access-key-info-ko-1.png
  docs/ko/GUIDE-img/access-key-info-ko-2.png
  docs/ko/GUIDE-img/account-info-1.png
  docs/ko/GUIDE-img/account-info-2.png
  docs/ko/GUIDE-img/account-info-3.png
  docs/ko/GUIDE-img/account-info-4.png
  docs/ko/GUIDE-img/account-info-5.png
  docs/ko/GUIDE-img/app-key-info-ko-1.png
  docs/ko/GUIDE-img/app-key-info-ko-2.png
  docs/ko/GUIDE-img/app-key-info-ko-3.png
  docs/ko/GUIDE-img/app-key-info-ko-4.png
  docs/ko/GUIDE-img/app-key-info-ko-5.png
  docs/ko/GUIDE-img/app-key-info-ko-6.png
  docs/ko/GUIDE-img/app-key-info-ko-7.png
  docs/ko/GUIDE-img/app-key-info-ko-8.png
  docs/ko/GUIDE-img/certificate-app-key-info-ko-1.png
  docs/ko/GUIDE-img/certificate-app-key-info-ko-2.png
  docs/ko/GUIDE-img/nhn-cloud.svg
  docs/ko/GUIDE-img/service-info-ko.png
  docs/ko/GUIDE-img/storage-access-key-info-ko-1.png
  docs/ko/GUIDE-img/storage-access-key-info-ko-2.png
  docs/ko/GUIDE.md
Labels: pass/signedoff

#55 Update dictionary key check
  src/plugin/manager/email/category_manager.py
  src/plugin/manager/email/tag_manager.py
  src/plugin/manager/email/template_manager.py
  src/plugin/manager/push/tag_manager.py
  src/plugin/manager/push/token_manager.py
Labels: pass/signedoff

#54 Add README for NHN Cloud Plugin
  README.md
Labels: documentation, pass/signedoff

#56 rename NKS service group, service type
  src/plugin/connector/nks/cluster_connector.py
  src/plugin/connector/nks/node_group_connector.py
  src/plugin/manager/__init__.py
  src/plugin/manager/nks/cluster_manager.py
  src/plugin/manager/nks/node_group_manager.py
  src/plugin/metadata/nks/cluster.yaml
  src/plugin/metadata/nks/node_group.yaml
Labels: enhancement, pass/signedoff
